# Site Settings
header_pages:
- mds/Main.md
- mds/Bio.md
- mds/Contacts.md
<<<<<<< HEAD
- mds/Current.md
- mds/Learning.md
=======
- mds/Abilities.md

>>>>>>> a21450fb3f524a3aa9965d0d4b8a376764fbe3de


style: dark
listen_for_clients_preferred_style: true

footer: 'Made by exoad | 2021 | Thanks for visiting! ;)'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
