# Site Settings
title: "Main"
header_pages:
- exoad/index.html
- exoad/html/Abilities.html
- exoad/html/Bio.html
- exoad/html/Contact.html

style: dark
listen_for_clients_preferred_style: true

footer: 'Made by exoad | 2021 | Thanks for visiting! ;)'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
